# .github/workflows/trivy_image_scan.yml
name: Image scan (Trivy)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4

      #- name: Build image
      #  run: |
      #    docker build -t lmcache/standalone:latest .

      - name: Run Trivy (image scan)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: lmcache/standalone:latest
          format: 'table'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          ignore-unfixed: true
          exit-code: '1'   # fail job if findings at selected severities
